apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i8a30757l-nodejs
  janus-idp.io/tekton: i8a30757l-nodejs
  backstage.io/kubernetes-id: i8a30757l-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i8a30757l-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
